language: python
python:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - nightly
install: python setup.py install
script: py.test
deploy:
  provider: pypi
  user: jorgebg
  password:
    secure: FQn9yyLT1mGS1v9ERHmXPwH07jAzQEXABM1G9zgJq+hnlpJ9wkKEgs3mKizHwCLB3qY5k9kvq1bto0BaKvodMBjQJsRdDh6k7lwMWCJtbb41EICK43f6x30TQaPbro44p+9PqCrDLQC3KF/L3uvo1mFRkZ3WMxFtmA4h6a5XAAM=
  on:
    tags: true
    repo: jorgebg/lumpy
